Bugfix quantity
AY2021S2-CS2113-T10-1/tp pull request #202
Opened 2021-04-04 13:52 UTC by SimJJ96

2021-04-04 16:14 UTC, Leeyp requested changes
LGTM

2021-04-04 16:14 UTC, Leeyp commented on src/main/java/seedu/fridgefriend/food/Fridge.java
> +        if (newQuantity >= Integer.MAX_VALUE) {
We might want to set the "MAX Value" not to integer max value, but rather a smaller value (perhaps 10k? 100k?) which would definitely prevent the case of Integer Overflows.

2021-04-04 16:23 UTC, Leeyp approved these changes
LGTM

2021-04-05 07:11 UTC, Vinci-Hu approved these changes
LGTM

2021-04-06 00:53 UTC, kwokyto approved these changes
Otherwise, LGTM

2021-04-06 00:53 UTC, kwokyto commented on src/main/java/seedu/fridgefriend/food/Fridge.java
> +        long oriQuantity = existingFood.getQuantity();
can we name this "originalQuantity" instead

2021-04-06 01:09 UTC, kwokyto commented on src/main/java/seedu/fridgefriend/food/Fridge.java
> +    private String exceedAddMessage = "Sorry my friend, "
can we change this and the one below to like "sorry my kawan"

2021-04-06 01:09 UTC, kwokyto commented on src/main/java/seedu/fridgefriend/exception/InvalidQuantityException.java
>      private static final String errorMessage = "Sorry my friend, the quantity "
can we change this to "sorry my kawan"

2021-04-06 06:53 UTC, merged